spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-zzc-dev
---
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-zzc-test