spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 7001
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client

eureka:
  instace:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7101
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client

eureka:
  instace:
    hostname: eureka7101.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7101/eureka/